from fastapi import APIRouter
from fastapi.responses import FileResponse

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet

from backend.database.db import SessionLocal
from backend.database.models import ImageAnalysis

import os

router = APIRouter()


def add_image(content, image_path, title, styles):

    if (
        image_path
        and os.path.exists(image_path)
    ):

        content.append(
            Paragraph(
                title,
                styles["Heading2"]
            )
        )

        img = Image(
            os.path.abspath(image_path)
        )

        max_width = 350

        img.drawWidth = max_width

        img.drawHeight = (
            img.imageHeight
            * (max_width / img.imageWidth)
        )

        content.append(img)

        content.append(
            Spacer(1, 10)
        )


@router.get("/report/{report_id}")
def generate_report(report_id: int):

    db = SessionLocal()

    try:

        report = (
            db.query(ImageAnalysis)
            .filter(
                ImageAnalysis.id == report_id
            )
            .first()
        )

        if not report:

            return {
                "error": "Data not found"
            }

        os.makedirs(
            "reports",
            exist_ok=True
        )

        pdf_path = os.path.abspath(
            f"reports/report_{report_id}.pdf"
        )

        doc = SimpleDocTemplate(
            pdf_path
        )

        styles = getSampleStyleSheet()

        content = []

        # =====================
        # TITLE
        # =====================

        content.append(
            Paragraph(
                "ForensiAI Investigation Report",
                styles["Title"]
            )
        )

        content.append(
            Spacer(1, 20)
        )

        # =====================
        # SUMMARY
        # =====================

        content.append(
            Paragraph(
                "Investigation Summary",
                styles["Heading2"]
            )
        )

        content.append(
            Paragraph(
                f"""
                Risk Level: <b>{report.risk}</b><br/>
                Authenticity Score:
                <b>{round(report.confidence * 100, 2)}%</b><br/>
                Mean ELA:
                <b>{report.mean_ela}</b><br/>
                Standard Deviation ELA:
                <b>{report.std_ela}</b><br/>
                """,
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 15)
        )

        # =====================
        # DETAIL INFORMATION
        # =====================

        fields = [
            ("Filename", report.filename),
            ("Camera", report.camera),
            ("Software", report.software),
            ("Risk", report.risk),
            ("Score", report.score),
            ("Confidence", report.confidence),
            ("Mean ELA", report.mean_ela),
            ("Std ELA", report.std_ela),
        ]

        content.append(
            Paragraph(
                "Analysis Details",
                styles["Heading2"]
            )
        )

        for label, value in fields:

            content.append(
                Paragraph(
                    f"<b>{label}</b>: {value}",
                    styles["Normal"]
                )
            )

        content.append(
            Spacer(1, 20)
        )

        # =====================
        # ORIGINAL IMAGE
        # =====================

        add_image(
            content,
            report.image_path,
            "Original Image",
            styles
        )

        # =====================
        # ELA IMAGE
        # =====================

        add_image(
            content,
            report.ela_path,
            "ELA Analysis",
            styles
        )

        # =====================
        # HEATMAP IMAGE
        # =====================

        if hasattr(report, "heatmap_path"):

            add_image(
                content,
                report.heatmap_path,
                "Forgery Heatmap",
                styles
            )

        # =====================
        # OVERLAY IMAGE
        # =====================

        if hasattr(report, "overlay_path"):

            add_image(
                content,
                report.overlay_path,
                "Overlay Visualization",
                styles
            )

        # =====================
        # FOOTER
        # =====================

        content.append(
            Spacer(1, 20)
        )

        content.append(
            Paragraph(
                "Generated by ForensiAI v0.8.2",
                styles["Italic"]
            )
        )

        # =====================
        # BUILD PDF
        # =====================

        doc.build(content)

        return FileResponse(
            pdf_path,
            media_type="application/pdf",
            filename=f"report_{report_id}.pdf"
        )

    except Exception as e:

        print(
            "REPORT ERROR:",
            str(e)
        )

        return {
            "error": str(e)
        }

    finally:

        db.close()