from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

import os


def add_resized_image(content, image_path):

    img = Image(image_path)

    max_width = 300

    img.drawWidth = max_width

    img.drawHeight = (
        img.imageHeight *
        (max_width / img.imageWidth)
    )

    content.append(img)

    content.append(
        Spacer(1, 15)
    )


def generate_report(data, output_path):

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    content = []

    # =====================
    # TITLE
    # =====================

    content.append(
        Paragraph(
            "ForensiAI Investigation Report",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    # =====================
    # SUMMARY
    # =====================

    content.append(
        Paragraph(
            "Investigation Summary",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            f"""
            Risk Level: <b>{data.get('Risk', '-')}</b><br/>
            Confidence: <b>{data.get('Confidence', '-')}</b><br/>
            Mean ELA: <b>{data.get('Mean ELA', '-')}</b><br/>
            Std ELA: <b>{data.get('Std ELA', '-')}</b><br/>
            """,
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    # =====================
    # TEXT INFORMATION
    # =====================

    text_fields = [
        "Filename",
        "Camera",
        "Software",
        "Risk",
        "Score",
        "Confidence",
        "Mean ELA",
        "Std ELA"
    ]

    for field in text_fields:

        if field in data:

            content.append(
                Paragraph(
                    f"<b>{field}</b>: {data[field]}",
                    styles["Normal"]
                )
            )

    content.append(
        Spacer(1, 20)
    )

    # =====================
    # ORIGINAL IMAGE
    # =====================

    if (
        "image_path" in data
        and os.path.exists(data["image_path"])
    ):

        content.append(
            Paragraph(
                "Original Image",
                styles["Heading2"]
            )
        )

        add_resized_image(
            content,
            data["image_path"]
        )

    # =====================
    # ELA ANALYSIS
    # =====================

    if (
        "ela_path" in data
        and os.path.exists(data["ela_path"])
    ):

        content.append(
            Paragraph(
                "ELA Analysis",
                styles["Heading2"]
            )
        )

        add_resized_image(
            content,
            data["ela_path"]
        )

    # =====================
    # HEATMAP ANALYSIS
    # =====================

    if (
        "heatmap_path" in data
        and os.path.exists(data["heatmap_path"])
    ):

        content.append(
            Paragraph(
                "Heatmap Analysis",
                styles["Heading2"]
            )
        )

        add_resized_image(
            content,
            data["heatmap_path"]
        )

    # =====================
    # OVERLAY VISUALIZATION
    # =====================

    if (
        "overlay_path" in data
        and os.path.exists(data["overlay_path"])
    ):

        content.append(
            Paragraph(
                "Overlay Visualization",
                styles["Heading2"]
            )
        )

        add_resized_image(
            content,
            data["overlay_path"]
        )

    # =====================
    # FOOTER
    # =====================

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by ForensiAI v0.8.2",
            styles["Italic"]
        )
    )

    doc.build(content)

    return output_path